### ISSUE TITLE
Packagist: Abandoned, no alternative

### ISSUE THREAD

**Issue by Xendiadyon** [contao-archive/contao#82]
https://packagist.org/packages/contao/contao
Maybe you should not simply abandon the contao/contao package, but forward it to https://github.com/contao/core-bundle

![image](https://cloud.githubusercontent.com/assets/2657385/25170956/8ce5b420-24ec-11e7-8ee9-1c06f4bce217.png)

**Comment by leofeyer** [comment]
> Maybe you should not simply abandon the contao/contao package, but forward it to https://github.com/contao/core-bundle

That would be wrong though. The correct replacement is:

```json
    "require": {
        "contao/calendar-bundle": "^4.3.2",
        "contao/comments-bundle": "^4.3",
        "contao/core-bundle": "^4.3.1",
        "contao/faq-bundle": "^4.3",
        "contao/installation-bundle": "^4.3.5",
        "contao/listing-bundle": "^4.3",
        "contao/news-bundle": "^4.3",
        "contao/newsletter-bundle": "^4.3",
    }
```
